### ISSUE TITLE
rofi_keepass - i3 exec Times Out Waiting For expect

### ISSUE THREAD

**Issue by Speff** [PMunch/Configuration#2]
Not sure if you still use this, but it looks like i3 isn't playing well with this script anymore. Trying to `exec` this script results in i3 timing out waiting for the script to return. 

`12/06/2019 08:21:36 PM - executing: rofi_keepass /home/speff/Documents/gen.kdbx`

`12/06/2019 08:22:36 PM - startup.c:startup_timeout:36 - Timeout for startup sequence i3/rofi_keepass/749-0-rokken_TIME2506044`

`12/06/2019 08:22:36 PM - startup.c:startup_monitor_event:238 - startup sequence i3/rofi_keepass/749-0-rokken_TIME2506044 completed`

`12/06/2019 08:22:36 PM - startup.c:startup_monitor_event:243 - Will delete startup sequence i3/rofi_keepass/749-0-rokken_TIME2506044 at timestamp 1575681786`

I suspect i3 isn't playing well with zenith? rofi_keepass runs correctly when running it in the terminal. The popup box doesn't show up when trying to run it from the keybind (`bindsym $mod+k exec rofi_keepass /home/speff/Documents/gen.kdbx`). I see a loading icon from i3 until it times out.

Vers:
i3-gaps: 4.17.1-1
kpcli: 3.3-1
expect: 5.45.4-1

**Comment by PMunch** [comment]
Hmm, I remember vaguely having similar issues with that script. Not entirely sure what caused them TBH. I've since switched for another script, written in Nim, for easier maintenance:

``` Nim
#!/usr/bin/env nimcr
import streams, strutils
import xmltree, xmlparser
import libkeepass
import osproc
import base64

template output(s: untyped) =
  discard execProcess("notify-send -u critical -a \"xlunch Keepass\" -i /usr/share/icons/papirus-arc-dark/48x48/apps/keepass2.svg \"" & s & "\"")
  stderr.write(s & "\n")

let
  pw = execProcess("zenity --password", options = {poUsePath, poEvalCommand})
  s = newFileStream("/home/peter/passwords.kdbx", fmRead)
if pw[0..^2] == "":
  output("No password entered!")
  quit 1
try:
  let
    db = readDatabase(s, pw[0..^2])
  echo "DB read"
  var
    passwords: seq[tuple[title, password: string]] = @[]
  for xml in db:
    for group in xml.child("Root"):
      proc parseGroup(group: XmlNode, path: string) =
        let name =
          if group.child("Name") == nil:
            ""
          else:
            if group.child("Name").innerText != "Root":
              #group.child("Name").innerText & "  "
              group.child("Name").innerText & " > "
            else:
              ""
        if group.tag == "Group":
          for entry in group:
            proc parseEntry(entry: XmlNode) =
              if entry.tag == "Entry":
                var title, password: string
                for field in entry:
                  case field.tag:
                  of "String":
                    let
                      keyTag = field.child("Key")
                      valueTag = field.child("Value")
                      key = keyTag.innerText
                      value = valueTag.innerText
                    case key:
                      of "Title":
                        title = path & name & value
                      of "Password":
                        password = value
                passwords.add((title: title,
                  password: password.multiReplace(
                    ("&lt;", "<"),
                    ("&gt;", ">"),
                    ("&amp;", "&"),
                    ("&quot;", "\""),
                    ("&#x27;", "'"),
                    ("&#x2F;", "/"))))
            if entry.tag == "Entry":
              parseEntry(entry)
            elif entry.tag == "Group":
              parseGroup(entry, path & name)
      parseGroup(group, "")
  var entries = ""
  for entry in passwords:
    entries = entries & entry.title & ";/usr/share/xlunch/svgicons/keepassxc.png;" & encode(entry.password) & "\n"
  entries = entries.multiReplace(("\"","\\\""),("$","\\$"))[0..^2]
  let chosen = execProcess("echo \"" & entries & "\" | xlunch-menu --prompt \"Entry: \"")
  #echo chosen
  #echo NimVersion
  #echo decode(chosen).multiReplace(("\"","\\\""),("$","\\$"))[0..^2]
  discard execProcess("xdotool type \"" & decode(chosen.multiReplace(("\"","\\\""),("$","\\$"))[0..^2]) & "\"")
except DecryptionException:
  output("Unable to decrypt database, wrong password?")
  quit 1
```

To use it simply install `choosenim` from here: https://nim-lang.org/install_unix.html and then run `nimble install nimcr libkeepass` to get the dependencies and then just set it as executable and run it (first time it takes a bit longer to run as it's compiling in the background).

EDIT: This uses [xlunch](http://xlunch.org) as well instead of rofi. Should be easy enough to change it back to use rofi, but since I'm one of the developers of xlunch I switched to that for all my small task choosing needs.

**Comment by PMunch** [comment]
Just updated the branch [dldesktop](https://github.com/PMunch/Configuration/tree/dldesktop) with something much closer to my current configuration.

**Comment by Speff** [comment]
Cool to see Nim out in the wild. I appreciate the update and I'll switch my config over. Thanks!

**Comment by PMunch** [comment]
Surprised to hear that you've even heard of it! Great language :)
